# Form implementation generated from reading ui file 'mmqgis_kml_export_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mmqgis_kml_export_form(object):
    def setupUi(self, mmqgis_kml_export_form):
        mmqgis_kml_export_form.setObjectName("mmqgis_kml_export_form")
        mmqgis_kml_export_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        mmqgis_kml_export_form.setEnabled(True)
        mmqgis_kml_export_form.resize(508, 395)
        mmqgis_kml_export_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_kml_export_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=mmqgis_kml_export_form)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_layer_name = QtWidgets.QComboBox(parent=mmqgis_kml_export_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.verticalLayout.addWidget(self.input_layer_name)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.separator = QtWidgets.QComboBox(parent=mmqgis_kml_export_form)
        self.separator.setObjectName("separator")
        self.gridLayout.addWidget(self.separator, 2, 1, 1, 1)
        self.name_field = QtWidgets.QComboBox(parent=mmqgis_kml_export_form)
        self.name_field.setObjectName("name_field")
        self.gridLayout.addWidget(self.name_field, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=mmqgis_kml_export_form)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=mmqgis_kml_export_form)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.label_2 = QtWidgets.QLabel(parent=mmqgis_kml_export_form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.description = QtWidgets.QTextEdit(parent=mmqgis_kml_export_form)
        self.description.setObjectName("description")
        self.verticalLayout.addWidget(self.description)
        self.export_data = QtWidgets.QCheckBox(parent=mmqgis_kml_export_form)
        self.export_data.setObjectName("export_data")
        self.verticalLayout.addWidget(self.export_data)
        self.label = QtWidgets.QLabel(parent=mmqgis_kml_export_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = QgsFileWidget(parent=mmqgis_kml_export_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(parent=mmqgis_kml_export_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=mmqgis_kml_export_form)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_kml_export_form)
        self.buttonBox.accepted.connect(mmqgis_kml_export_form.accept) # type: ignore
        self.buttonBox.rejected.connect(mmqgis_kml_export_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mmqgis_kml_export_form)
        mmqgis_kml_export_form.setTabOrder(self.input_layer_name, self.name_field)
        mmqgis_kml_export_form.setTabOrder(self.name_field, self.separator)
        mmqgis_kml_export_form.setTabOrder(self.separator, self.buttonBox)

    def retranslateUi(self, mmqgis_kml_export_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_kml_export_form.setWindowTitle(_translate("mmqgis_kml_export_form", "Google Maps KML Export"))
        self.label_4.setText(_translate("mmqgis_kml_export_form", "Input Layer"))
        self.label_3.setText(_translate("mmqgis_kml_export_form", "Placemark Name Field"))
        self.label_5.setText(_translate("mmqgis_kml_export_form", "Description Separator"))
        self.label_2.setText(_translate("mmqgis_kml_export_form", "Placemark Description HTML"))
        self.export_data.setText(_translate("mmqgis_kml_export_form", "Export attributes as <Data> (importable by QGIS)"))
        self.label.setText(_translate("mmqgis_kml_export_form", "Output KML File"))
        self.output_file_name.setFilter(_translate("mmqgis_kml_export_form", "Shapefile (*.shp)"))
from qgsfilewidget import QgsFileWidget
