# Form implementation generated from reading ui file 'mmqgis_geocode_reverse_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mmqgis_geocode_reverse_form(object):
    def setupUi(self, mmqgis_geocode_reverse_form):
        mmqgis_geocode_reverse_form.setObjectName("mmqgis_geocode_reverse_form")
        mmqgis_geocode_reverse_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        mmqgis_geocode_reverse_form.setEnabled(True)
        mmqgis_geocode_reverse_form.resize(433, 308)
        mmqgis_geocode_reverse_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_geocode_reverse_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=mmqgis_geocode_reverse_form)
        self.label_4.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_layer_name = QtWidgets.QComboBox(parent=mmqgis_geocode_reverse_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.verticalLayout.addWidget(self.input_layer_name)
        self.label_3 = QtWidgets.QLabel(parent=mmqgis_geocode_reverse_form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.web_service = QtWidgets.QComboBox(parent=mmqgis_geocode_reverse_form)
        self.web_service.setObjectName("web_service")
        self.verticalLayout.addWidget(self.web_service)
        self.api_key_label = QtWidgets.QLabel(parent=mmqgis_geocode_reverse_form)
        self.api_key_label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.api_key_label.setObjectName("api_key_label")
        self.verticalLayout.addWidget(self.api_key_label)
        self.api_key = QtWidgets.QLineEdit(parent=mmqgis_geocode_reverse_form)
        self.api_key.setObjectName("api_key")
        self.verticalLayout.addWidget(self.api_key)
        self.label_6 = QtWidgets.QLabel(parent=mmqgis_geocode_reverse_form)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.duplicate_handling = QtWidgets.QComboBox(parent=mmqgis_geocode_reverse_form)
        self.duplicate_handling.setObjectName("duplicate_handling")
        self.verticalLayout.addWidget(self.duplicate_handling)
        self.label = QtWidgets.QLabel(parent=mmqgis_geocode_reverse_form)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = QgsFileWidget(parent=mmqgis_geocode_reverse_form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.output_file_name.sizePolicy().hasHeightForWidth())
        self.output_file_name.setSizePolicy(sizePolicy)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(parent=mmqgis_geocode_reverse_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=mmqgis_geocode_reverse_form)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_geocode_reverse_form)
        self.buttonBox.accepted.connect(mmqgis_geocode_reverse_form.accept) # type: ignore
        self.buttonBox.rejected.connect(mmqgis_geocode_reverse_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mmqgis_geocode_reverse_form)

    def retranslateUi(self, mmqgis_geocode_reverse_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_geocode_reverse_form.setWindowTitle(_translate("mmqgis_geocode_reverse_form", "Reverse Geocode"))
        self.label_4.setText(_translate("mmqgis_geocode_reverse_form", "Input Layer Name"))
        self.label_3.setText(_translate("mmqgis_geocode_reverse_form", "Web Service"))
        self.api_key_label.setText(_translate("mmqgis_geocode_reverse_form", "Google API Key"))
        self.label_6.setText(_translate("mmqgis_geocode_reverse_form", "Duplicate Results Handling"))
        self.label.setText(_translate("mmqgis_geocode_reverse_form", "Output File Name"))
from qgsfilewidget import QgsFileWidget
