# Form implementation generated from reading ui file 'mmqgis_voronoi_form.ui'
#
# Created by: PyQt6 UI code generator 6.10.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mmqgis_voronoi_form(object):
    def setupUi(self, mmqgis_voronoi_form):
        mmqgis_voronoi_form.setObjectName("mmqgis_voronoi_form")
        mmqgis_voronoi_form.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        mmqgis_voronoi_form.setEnabled(True)
        mmqgis_voronoi_form.resize(383, 164)
        mmqgis_voronoi_form.setMouseTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(mmqgis_voronoi_form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_4 = QtWidgets.QLabel(parent=mmqgis_voronoi_form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.input_layer_name = QtWidgets.QComboBox(parent=mmqgis_voronoi_form)
        self.input_layer_name.setObjectName("input_layer_name")
        self.verticalLayout.addWidget(self.input_layer_name)
        self.label = QtWidgets.QLabel(parent=mmqgis_voronoi_form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.output_file_name = QgsFileWidget(parent=mmqgis_voronoi_form)
        self.output_file_name.setObjectName("output_file_name")
        self.verticalLayout.addWidget(self.output_file_name)
        self.status = QtWidgets.QProgressBar(parent=mmqgis_voronoi_form)
        self.status.setProperty("value", 24)
        self.status.setObjectName("status")
        self.verticalLayout.addWidget(self.status)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=mmqgis_voronoi_form)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Apply|QtWidgets.QDialogButtonBox.StandardButton.Close)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(mmqgis_voronoi_form)
        self.buttonBox.accepted.connect(mmqgis_voronoi_form.accept) # type: ignore
        self.buttonBox.rejected.connect(mmqgis_voronoi_form.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(mmqgis_voronoi_form)
        mmqgis_voronoi_form.setTabOrder(self.input_layer_name, self.buttonBox)

    def retranslateUi(self, mmqgis_voronoi_form):
        _translate = QtCore.QCoreApplication.translate
        mmqgis_voronoi_form.setWindowTitle(_translate("mmqgis_voronoi_form", "Voronoi Diagram"))
        self.label_4.setText(_translate("mmqgis_voronoi_form", "Source Layer"))
        self.label.setText(_translate("mmqgis_voronoi_form", "Output File Name"))
from qgsfilewidget import QgsFileWidget
